# Alterar a porta: server.port: 8081

# Dados do banco
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    
default:
  sender: filipe.xavier1928@gmail.com
  recipient: filipe.xavier1928@gmail.com
  
