# Alterar a porta: server.port: 8081

# Dados do banco
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
  
  # Configurações de envio de e-mail
  mail:
    host: 
    username: 
    password: 
    
    properties.mail.smtp:
      auth: true
      socketFactory:
        port: 
        class: javax.net.ssl.SSLSocketFactory
        fallback: false
      
      starttls.enable: true
      ssl.enable: true