spring:
  profiles:
    active: prod
    
default:
  sender: ${EMAIL_USERNAME}
  recipient: ${EMAIL_USERNAME}

# Sequencia De Caracteres Para Assinar Token
jwt.secret: ${JWT_SECRET}
jwt.expiration: 60000

dropbox.acess:
  token: ${DROPBOX_TOKEN}
  folder_name: ${DROPBOX_FOLDER_NAME}